apps/task/urls.py
from django.urls import path

from task import views

urlpatterns = [
    path('', views.tasks_view, name='tasks_view'),
    path('create/', views.task_create, name='task_create'),
    path('create/<int:obj_id>/', views.task_create, name='task_create'),
    path('<int:task_id>/edit/', views.task_edit, name='task_edit'),
    path('<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('<int:task_id>/file/<int:file_id>/edit_file/', views.edit_file_task, name='edit_file_task'),
    path('<int:task_id>/file/del/', views.del_file_task, name='del_file_task'), # file id in POST
    #url(r'^list_task$', views.tasks_view, name='tasks_view'),
    path('create_task/<int:task_id>/', views.task_create_task, name='task_create_task'),
    path('<int:task_id>/task/del/', views.del_task_child, name='del_task_child'),
    path('<int:parent_id>/task/up/', views.up_level_task_child, name='up_level_task_child'),
]

common/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.utils import timezone
from django.views.decorators.http import last_modified
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from haystack.views import search_view_factory
from invent.forms import ImageSearchForm
from invent import views
from proj import views as proj_views

handler500 = 'proj.views.server_error'
last_modified_date = timezone.now()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taxo/',  include('apps.taxo.urls')),
    path('task/', include('task.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('jsi18n/', last_modified(lambda req, **kw: last_modified_date)(JavaScriptCatalog.as_view()),
        name='javascript_catalog'),

    path('login/', auth_views.LoginView.as_view(template_name='proj/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    re_path(r'^users/(?P<username>[\w@\.\-]+)/$', proj_views.profile, name='profile'),
    re_path(r'^setlang/(?P<lang>\w+)/$', proj_views.set_language, name='setlang'),
    path('site_admin/', proj_views.site_admin, name='site_admin'),
    path('help/', proj_views.help_index, name='help_index'),
    path('help/<subject>/', proj_views.help, name='help'),

    path('', views.IndexView.as_view(), name='home'),

    path('search/', views.SearchView.as_view(), name='search'),
    path('search/export', views.search_export, name='search-export'),
    path('search/add_criterion/<int:base_num>/', views.add_criterion, name='add_criterion'),
    path('search_images/', search_view_factory(
        view_class=views.ImageSearchView,
        form_class=ImageSearchForm,
        template='search/search_images.html'), name='search_img'),

    #Duplicate accession after the germination.
    path('invent/<int:object_id>/duplicate/', views.accession_duplicate, name='accession_duplicate'),

    path('invent/', views.invent_list, name='inventories'),
    path('invent/autocomplete/', views.object_autocomplete, name='baseobject_autocomplete'),
    path('invent/<int:parent_id>/new/<obj_code>/', views.ObjectCreateView.as_view(), name='object_create'),
    path('invent/<int:obj_id>/', views.ObjectDetailView.as_view(), name='object_detail'),
    path('invent/<int:obj_id>/as_image/', views.object_image, name='object_image'),
    path('invent/<int:obj_id>/edit/', views.ObjectEditView.as_view(), name='object_edit'),
    path('invent/<int:obj_id>/editperms/', views.object_edit_perms, name='object_edit_perms'),
    path('invent/<int:obj_id>/delete/', views.object_delete, name='object_delete'),
    re_path(r'^invent/(?P<obj_id>\d+)/contents/(?P<otype>[-\w]+)?/?$',
        views.PaginatedObjectsView.as_view(), name='object_list'),
    re_path(r'^invent/(?P<obj_id>\d+)/contents/(?P<otype>[-\w]+)/(?P<format>(table|geojson))/$',
        views.object_list_table, name='object_list_table'),
    re_path(r'^invent/by_uuid/(?P<uuid>[-\w]+)/(?P<format>(html|json|xml))?/?$',
        views.object_list_by_uuid, name='object_by_uuid'),
    path('invent/<int:obj_id>/export/lots/', views.ObjectExportLots.as_view(), name='object_export_lots'),
    path('invent/<int:obj_id>/import/', views.object_import, name='object_import'),
    path('attributes/', views.attributes, name='attributes'),
    # attribute name passed in GET
    path('attributes/vocab/', views.vocab_for_attribute, name='vocab_for_attribute'),

    re_path(r'^attributes_in_group/(?P<group_id>-?\d+)/$', views.attributes_in_group),

    # CRUD for Lots and GermTests
    path('accession/<int:pk>/new_lot/', views.LotEditView.as_view(create=True), name='lot_create'),
    path('lot/<int:pk>/edit/', views.LotEditView.as_view(), name='lot_edit'),
    path('lot/<int:pk>/delete/', views.LotDeleteView.as_view(), name='lot_delete'),
    path('lot/<int:pk>/new_test/', views.GermTestEditView.as_view(create=True), name='test_create'),
    path('germtest/<int:pk>/edit/', views.GermTestEditView.as_view(), name='test_edit'),
    path('germtest/<int:pk>/delete/', views.GermTestDeleteView.as_view(), name='test_delete'),
    path('command/<int:lot_pk>/create/', views.CommandEditView.as_view(create=True), name='command_create'),
    path('command/<int:pk>/edit/', views.CommandEditView.as_view(), name='command_edit'),
    path('command/<int:pk>/delete/', views.CommandDeleteView.as_view(), name='command_delete'),

    path('<int:object_id>/value/new/<int:attr_id>/', views.add_value, name='add_value'),
    re_path(r'^(?P<object_id>\d+)/value/(?P<value_id>[\w\-]+)/edit/$', views.edit_value),
    path('<int:object_id>/value/del/', views.del_value, name='del_value'), # value id in POST
    # Image and file attachment editing
    path('<int:object_id>/photo/add/', views.add_photo, name="add_photo"),
    path('<int:object_id>/file/<int:file_id>/edit/', views.edit_file, name='edit_file'),
    path('<int:object_id>/file/del/', views.del_file), # file id in POST
]

if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

apps/task/models.py
from datetime import date

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.staticfiles import finders
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.templatetags.static import static
from django.urls import reverse
from django.utils.translation import gettext as _

from invent.models import BaseObject, Attribute, ObjectValue, date_validator, value_render


class TaskAuto(models.Model):
    text = models.TextField()
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    value_text = models.TextField(blank=True)
    
    class Meta:
        db_table = "task_auto"

    def __str__(self):
        return self.text


class Task(models.Model):
    text = models.TextField("Tâche", null = False, blank = False)
    done = models.BooleanField("Terminé", null = False)
    obj = models.ForeignKey(BaseObject, null=True, on_delete=models.CASCADE)
    auto = models.ForeignKey(TaskAuto, null=True, on_delete=models.CASCADE)
    deadline = models.DateField("Echéance", null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    files = GenericRelation('invent.FileAttachment')
    
    class Meta:
        db_table = "task"

    def status(self):
        if self.done:
            return "done" # green
        elif self.deadline == None:
            return "unknown" # gray
        elif self.deadline <= date.today():
            return "late" # red
        else:
            return "early" # yellow

    def __str__(self):
        return self.text or str(self.pk)
    
    def get_text(self):
        return str(self)
        
    def get_absolute_url(self):
        return reverse('task_edit', args=[str(self.id)])
            
    def breadcrumb(self, link_self=False):
        """ Produce a tuple list structure to give to template to build the breadcrumb """
        bc_list = [(_("Home"), "/")]
        bc_list.append((self.get_text(), link_self and self.get_absolute_url() or ""))
        return bc_list


@receiver(post_save)
def ObjectValue_post_save(sender, instance, created, **kwargs):
    if not isinstance(instance, ObjectValue):
        return
    for auto in TaskAuto.objects.filter(attribute = instance.attr):
        try:
            task = Task.objects.get(obj = instance.obj, auto = auto)
        except Task.DoesNotExist:
            task = Task(obj = instance.obj, auto = auto)
            task.text = auto.text
            task.done = False
            task.owner = instance.obj.owner
        if instance.attr.datatype == 'date':
            try:
                task.deadline = date_validator(instance.value_text)
            except ValidationError:
                pass
        task.save()

@receiver(pre_delete, sender = ObjectValue)
def ObjectValue_pre_delete(sender, instance, **kwargs):
    Task.objects.filter(obj = instance.obj, auto__attribute = instance.attr).delete()

@receiver(value_render)
def ObjectValue_render(sender, result, **kwargs):
    for task in Task.objects.filter(obj = sender.obj, auto__attribute = sender.attr, done = False):
        result.append('<div><img src="%s"> %s</div>' % (static('img/%s.png' % task.status()), task.text))

apps/task/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import gettext as _
from .models import Task

class TaskForm(forms.ModelForm):
    deadline = forms.DateField(label = "Echéance", input_formats = ['%d.%m.%Y', '%Y-%m-%d', '%d/%m/%Y'], required = False)
    class Meta:
        model = Task
        fields = ('deadline', 'text', 'done')

apps/task/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.dispatch import receiver, Signal
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST

from invent.views import value_edit_post_init, value_edit_post_save
from invent.models import BaseObject, FileAttachment
from invent.forms import FileForm

from .models import TaskAuto, Task
from .forms import TaskForm

from datetime import date

HOME_TUPLE = (_("Home"), "/")

@login_required
def task_create(request, obj_id = None):
    task = Task()
    task.owner = request.user
    
    if obj_id:
        task.obj = BaseObject.objects.get(id = obj_id)
        
    return task_edit_form(request, task)

@login_required
def task_create_task(request, task_id):
    task = Task()
    task.owner = request.user
    task.parent = Task.objects.get(id = task_id)
    
    return task_edit_form(request, task)
    
@login_required
def task_edit(request, task_id):
    task = get_object_or_404(Task, id = task_id)
    
    return task_edit_form(request, task)

def task_edit_form(request, task):
    editable = True
    if request.method == 'POST':
        form = TaskForm(request.POST, instance = task)
        
        if form.is_valid():
            obj = task.obj
            
            if not form.instance.owner_id:
                form.instance.owner = request.user
            form.save()
            return HttpResponseRedirect(obj and obj.get_absolute_url() or '/')
    else:
        form = TaskForm(instance = task)

    context = {
        'task': task,
        'form': form,
        'editable': editable,
        'breadcrumb':  task and task.breadcrumb() or [HOME_TUPLE, (_("Create task"), "")],
    }
    return render(request, 'task/task_edit.html', context)


@login_required
def task_delete(request, task_id):
    if request.method == 'POST':
        task = get_object_or_404(Task, pk=task_id)
        obj = task.obj
        task.delete()
        messages.success(request, _("The task was successfully deleted."))
        return HttpResponseRedirect(obj.get_absolute_url())


@login_required
def tasks_view(request):
    tasks = Task.objects.all()
        
    def sort_key(task):
        return (task.deadline or date.today(), task.text)
        
    tasks = sorted(tasks, key = sort_key)
    
    context = {
        'tasks': tasks,
         'breadcrumb': [HOME_TUPLE, (_("Task Edition"), "")],
    }
        
    return render(request, 'task/tasks_view.html', context)

@receiver(value_edit_post_init)
def post_init(sender, form, obj, attr, value, **kwargs):
    for auto in TaskAuto.objects.filter(attribute = attr):
        try:
            done = Task.objects.get(obj = obj, auto = auto).done
        except Task.DoesNotExist:
            done = False
        form.fields['auto_%i' % auto.id] = forms.BooleanField(label = auto.text, initial = not done, required = False)

@receiver(value_edit_post_save)
def post_save(sender, form, obj, attr, value, **kwargs):
    for auto in TaskAuto.objects.filter(attribute = attr):
        task = Task.objects.get(obj = obj, auto = auto)
        task.done = not form.cleaned_data['auto_%i' % auto.id]
        task.save()
        
def edit_file_task(request, task_id, file_id):
    task = get_object_or_404(Task, pk=task_id)
    file_id = int(file_id)
    file_obj = None
    
    if file_id > 0:
        file_obj = FileAttachment.objects.get(pk=file_id)
        
    if request.method == 'POST':
        file_form = FileForm(request.POST, request.FILES, instance=file_obj)
        
        if file_form.is_valid():                
            file_form.save(task)
            return HttpResponseRedirect(task.get_absolute_url())
    else:
        file_form = FileForm(instance=file_obj)
    context = {
        'task': task,
        'photo': file_obj,
        'form': file_form,
        'breadcrumb': task and task.breadcrumb(),
    }
    return render(request, 'task/task_file_edit.html', context)

def del_file_task(request, task_id):
    return del_element(request, task_id, FileAttachment)

def del_task_child(request, task_id):
    return del_element(request, task_id, Task)
    
@require_POST
def del_element(request, task_id, DelModel):
    """ Delete an attribute value from a task """
    task = get_object_or_404(Task, pk=task_id)
        
    try:
        pk = int(request.POST['id_to_delete'])
        value = get_object_or_404(DelModel, pk=pk)
    except ValueError:
        attr = get_object_or_404(Attribute, name=request.POST['id_to_delete'])
    value.delete()
    return HttpResponse("")

@require_POST
def up_level_task_child(request, parent_id):
    """ Up level for task child """
    task_parent = get_object_or_404(Task, pk=parent_id)
    
    try:
        pk_child = int(request.POST['id_to_up_level'])
        task_child = get_object_or_404(Task, pk=pk_child)
        
        if task_parent.parent:
            task_child.parent = task_parent.parent
        else:
            task_child.parent = None
        task_child.save()
        
    except ValueError:
        value_error = request.POST['id_to_up_level']
        
    return HttpResponse("")

templates/task/list_tasks.html
{% load i18n %}

<div class="object_block_right">
    <h2 class="object_block_title">{% trans "Task" %}</h2>
    <div class="child" id="child-{{ child.id }}">
        <ul style="margin: 0; padding-left: 3em;">
            {% for child in task.children.all %}
                <li class="task_li {% cycle 'odd' 'even' %} task-{{child.status}}">{{ child.deadline|date:"d.m.Y" }}&nbsp;&nbsp;{{ child.text }}
                        
                    {% if editable %}
                        <a href="." onclick="return up_level_task({{ child.id }})">
                            <img class="edit_icon" src="{% static 'img/uparrow.png' %}" height="16" title="{% trans "Up level" %}" alt="up icon">
                        </a>
                        <a href="{% url 'task_edit' child.id %}">
                            <img class="edit_icon" src="{% static '}img/edit.png' %}" height="16" title="{% trans "Edit" %}" alt="edit icon">
                        </a>
                        <a href="." onclick="return delete_task_child({{ child.id }})">
                            <img class="edit_icon" src="{% static 'img/delete.png' %}" height="16" title="{% trans "Delete" %}" alt="delete icon">
                        </a>
                    {% endif %}
                    
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/task/obj_tasks.html
{% load i18n %}

{% if user.is_authenticated and obj.task_set and obj.task_set.all %}
  <div class="object_block_{% cycle 'right' 'left' %}">
    <h2 class="object_block_title">{% trans "Tasks" %}</h2>
    <div class="object_block_content">
      <ul style="margin: 0; padding-left: 3em;">
        {% for task in obj.task_set.all %}
            {% include "task/task.html" %}
        {% endfor %}
      </ul>
    </div>
  </div>
{% endif %}

templates/task/task.html
{% load i18n objects %}

<li class="{% cycle 'odd' 'even' %} task-{{task.status}}">
  {{ task.deadline|date:"d.m.Y" }}
  {% if task.obj and not obj %}
    <span class="status-{{ task.obj.status }}">{{ task.obj|resume:'short' }}</span>
  {% endif %}
 
   <a href="{% url 'task_edit' task.id %}">{{ task.text|title }}</a>
</li>

templates/task/task_edit.html
{% extends "base.html" %}
{% load i18n objects %}

{% block extra_head %}
    <script>
        var task_id = {% if task.pk %}{{ task.id }}{% else %}{{ 0 }}{% endif %};
        var editable = {{ editable|yesno:"true,false" }};
        
         $(document).ready(function() {
              function attr_edit_btns() {
                $("li.task_li").hoverIntent(function(){
                  $(this).find("img").show();
                }, function() {
                  $("img.edit_icon").hide();
                });
            }
            attr_edit_btns();
         });
    </script>
    {% if editable %}
        <script src="{% url 'javascript_catalog' %}"></script>
        <script src="{{ STATIC_URL }}task/js/task_edit.js"></script>
    {% endif %}    
{% endblock %}

{% block title %}
  {% if task.pk %}
    {% trans "Edit Task" %}
  {% else %}
    {% trans "Create Task" %}
  {% endif %}
{% endblock %}

{% block content %}

  {% if task.pk %}
    <h1>{% trans "Edit Task" %}</h1>
    
  {% else %}
    <h1>{% trans "Create Task" %}</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table class="form">
      <tbody>
        {% if task.obj %}
          <tr>
            <th>{% trans "Object:" %}</th>
            <td>{{ task.obj|resume:'short' }}</td>
          </tr>
        {% endif %}
        {{ form.as_table }}
        <tr>
          <td colspan="2" align="right">
            <input type="button" onclick="history.go(-1)" value="{% trans 'Cancel' %}">
            <input type="submit" value="{% if task.pk %}{% trans 'Modify' %}{% else %}{% trans 'Create' %}{% endif %}">
            {% if task.pk %}
            <br>
            <button type="submit" class="delete" formaction="{% url 'task_delete' task.pk %}">{% trans 'Delete' %}</button>
            {% endif %}
          </td>
        </tr>
      </tbody>
    </table>
  </form>

     {% if task.pk %}
        {% if task.files.count %}
            {% include "task/task_files.html" %}
        {% endif %}
        {% if task.children.count %}
            {% include "task/list_tasks.html" %}
        {% endif  %} 
    {% endif %}
{% endblock %}

{% block edit_widgets %}
    {% if task.pk %}
        <div class="edit_buttons">
            <a href="{% url 'edit_file_task' task.id "0" %}">
                <img src="{{ STATIC_URL }}img/plus.png" alt="plus sign" class="icon">&nbsp;{% trans "File…" %}
            </a><br>
            
            <a href="{% url 'task_create_task' task.id %}">
                <img src="{{ STATIC_URL }}img/plus.png" alt="plus sign" class="icon">&nbsp;{% trans "Task…" %}
            </a><br>
        </div>
    {% endif %}
{% endblock %}

templates/task/task_file_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "File attachments"%}{% endblock %}

{% block content %}

<h1>{{ object.title }} - {% if file_obj %}{% trans "Edit attachment" %}{% else %}{% trans "Add attachment" %}{% endif %}</h1>
 
<form enctype="multipart/form-data" method="post" action=".">
{% if file_obj %}<div style="float:right"><img src="{{ file.file }}" width="100" /></div>
{% endif %}
<table class="form">
{{ form.as_table }}
<tr><td colspan="2" align="right">
    <input type="button" onclick="history.go(-1)" value="{% trans "Cancel"%}" />
    <input type="submit" value="{% if not file_obj %}{% trans "Add"%}{% else %}{% trans "Modify" %}{% endif %}" />
</td></tr>
</table>
</form>

{% endblock %}

templates/task/task_files.html
{% load i18n %}

<div class="object_block_left"> 
    <h2 class="object_block_title">{% trans "Files" %}</h2>
    
    {% for file in task.files.all %}
         <div class="file" id="file-{{ file.id }}">
            <ul style="margin: 0; padding-left: 3em;">
                    
                    <li class="task_li {% cycle 'odd' 'even' %} task-{{file.status}}">
                        <a href="{{ file.fil.url }}" title="{% trans "Download" %}"><img src="{{ file.get_icon }}" />{{ file.title }}</a>
                
                            {% if editable %}
                                <a href="{% url 'edit_file_task' task.id file.id %}">
                                    <img class="edit_icon" src="{{ STATIC_URL}}img/edit.png" height="16" title="{% trans "Edit" %}" alt="edit icon" /></a>
                                <a href="." onclick="return delete_file_task({{ file.id }})">
                                    <img class="edit_icon" src="{{ STATIC_URL}}img/delete.png" height="16" title="{% trans "Delete" %}" alt="delete icon" /></a>
                            {% endif %}

                    </li>
            </ul>
        </div>
    {% endfor %}
</div>

templates/task/tasks_block.html
{% load i18n  %}
<div class="block half_block" >
  <h2><a href="{% url 'tasks_view' %}">{% trans "Tasks" %}</a></h2>
  <div class="block_content">
    <ul style="max-height: 30em; overflow: auto">
      {% for task in tasks %}
        {% include "task/task.html" %}
      {% endfor %}
    </ul>
    <p><a href="{% url 'task_create' %}" id="create_link"><img src="{% static 'img/plus.png' %}" alt="plus sign">&nbsp;<em>{% trans "Create..." %}</em></a></p>
  </div>
</div>

templates/task/tasks_view.html
{% load i18n objects tasks %}

{% block title %}
  {% trans "Tasks" %}
{% endblock %}

{% block content %}

  <h1>{% trans "Tasks" %}</h1>
  <ul>
    {% for task in tasks %}       
      <li class="{% cycle 'odd' 'even' %} task-{{task.status}}">
        {{ task.deadline|date:"d.m.Y" }}
        {% if task.obj %}
          <span class="status-{{ task.obj.status }}">{{ task.obj|resume:'short' }}</span>: {{ task.text }}
        {% else %}
          <a href="{% url 'task_edit' task.id %}">{{ task.text }}</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>

{% endblock %}